name: stardust_soul
description: "Unveiling a holistic AI wellness companion designed for youth, this project blends empathetic chat, a unique \\\"Emotion Galaxy\\\" for visual mood tracking, gamified challenges, and a robust progress tracker to foster mental well-being and personal growth."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  audioplayers: ^6.0.0
  url_launcher: ^6.0.0
  flutter_tts: ^4.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  shared_preferences: ^2.0.0
  http: ^1.0.0
  intl: 0.20.2
  firebase_core: ^4.1.0
  firebase_auth: '>=5.3.3'
  cloud_firestore: '>=5.5.0'
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
