// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_78CZK1nannBNyAcASs0NuQv7S6E05mo',
    appId: '1:381193447563:web:75428ef79089b811970c8e',
    messagingSenderId: '381193447563',
    projectId: 'fir-a79ce',
    authDomain: 'fir-a79ce.firebaseapp.com',
    storageBucket: 'fir-a79ce.firebasestorage.app',
    measurementId: 'G-9C4J6RDWH4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn50ZBfEUdGTbAxeyULtLZrVFXpMGIZQM',
    appId: '1:381193447563:android:37426ef5cae33128970c8e',
    messagingSenderId: '381193447563',
    projectId: 'fir-a79ce',
    storageBucket: 'fir-a79ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3KAGuaqltczmUeE9Vw-WyGRxrUGmkHK8',
    appId: '1:381193447563:ios:e9f405730101d191970c8e',
    messagingSenderId: '381193447563',
    projectId: 'fir-a79ce',
    storageBucket: 'fir-a79ce.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
